"""
Caching infrastructure.

Architecture
------------

Application Service
        │
        ▼
CachedRepository
        │
        ├──────────────► MultiLevelCache
        │                     │
        │                ┌────┴────┐
        │                ▼         ▼
        │           MemoryCache  RedisCache
        │
        ▼
Repository (SQLAlchemy / InMemory)
        │
        ▼
Database

Design principles
-----------------
- Cache implements a generic key-value storage.
- CachedRepository implements the Cache-Aside pattern.
- MultiLevelCache implements a read-through L1/L2 cache.
- L1 is an in-process memory cache.
- L2 is a distributed Redis cache.
- Cache keys are generated by a dedicated CacheKeyBuilder.
- Repository methods invalidate cache entries instead of updating them.
- Entity, collection and pagination caches are independent and use different keys.
"""


from typing import Protocol

import asyncio
import contextlib
import logging
import time
import uuid
from uuid import UUID

from redis.asyncio import Redis

from ..domain.entities import Entity
from ..domain.repos import Repository, RepositoryDecorator

logger = logging.getLogger(__name__)


def build_key(prefix: str, uid: uuid.UUID) -> str:
    return f"{prefix}:{uid}"


class Cache[T](Protocol):

    async def get(self, key: str) -> T | None: ...

    async def set(self, key: str, value: T) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...


class Serializer[T](Protocol):

    def dumps(self, value: T) -> bytes: ...

    def loads(self, value: bytes) -> T: ...


class RedisCache[T](Cache[T]):
    serializer: Serializer[T]

    def __init__(self, redis: Redis, ttl: int | None = None) -> None:
        self.redis = redis
        self.ttl = ttl

    async def get(self, key: str) -> T | None:
        if (raw := await self.redis.get(key)) is None:
            return None

        return self.serializer.loads(raw)

    async def set(self, key: str, value: T) -> None:
        raw = self.serializer.dumps(value)
        await self.redis.set(key, raw, ex=self.ttl)

    async def delete(self, key: str) -> None:
        await self.redis.delete(key)

    async def exists(self, key: str) -> bool:
        result = await self.redis.exists(key)
        return result > 0


class InMemoryCache[T](Cache[T]):
    def __init__(self, ttl: float | None = None, cleanup_interval: float = 60) -> None:
        self.storage: dict[str, tuple[T, float | None]] = {}
        self.ttl = ttl
        self.cleanup_interval = cleanup_interval
        self._cleanup_task: asyncio.Task[None] | None = None

    async def get(self, key: str) -> T | None:
        """Получение с ленивым удалением по TTL."""

        if key not in self.storage:
            return None

        value, expires = self.storage[key]
        if expires is not None and time.monotonic() >= expires:
            del self.storage[key]
            return None

        return value

    async def set(self, key: str, value: T) -> None:
        expires = None

        if self.ttl:
            expires = time.monotonic() + self.ttl

        self.storage[key] = (value, expires)

    async def delete(self, key) -> None:
        if key not in self.storage:
            return

        del self.storage[key]

    async def exists(self, key: str) -> bool:
        return key in self.storage

    async def _cleanup_loop(self) -> None:
        """Бесконечный цикл для отчистки протухшего кеша по TTL."""

        while True:
            await asyncio.sleep(self.cleanup_interval)

            now = time.monotonic()

            expired = [
                key
                for key, (value, expires) in self.storage.items()
                if expires is not None and expires <= now
            ]

            for key in expired:
                if key in self.storage:
                    del self.storage[key]

    def start(self) -> None:
        self._cleanup_task = asyncio.create_task(self._cleanup_loop())

    async def close(self) -> None:
        if self._cleanup_task is None:
            return

        self._cleanup_task.cancel()

        with contextlib.suppress(asyncio.CancelledError):
            await self._cleanup_task


class MultiLevelCache[T](Cache[T]):
    def __init__(self, l1_cache: Cache[T], l2_cache: Cache[T]) -> None:
        self.l1_cache = l1_cache
        self.l2_cache = l2_cache

    async def get(self, key: str) -> T | None:
        """В случае промаха L1, устанавливает значение в L1, если нашёлся в L2."""

        if (value := await self.l1_cache.get(key)) is not None:
            return value

        if (value := await self.l2_cache.get(key)) is not None:
            await self.l1_cache.set(key, value)
            return value

        return None

    async def set(self, key: str, value: T) -> None:
        """Параллельно пишет кеш в два слоя L1 и L2."""

        try:
            async with asyncio.TaskGroup() as tg:
                tg.create_task(self.l1_cache.set(key, value))
                tg.create_task(self.l2_cache.set(key, value))
        except ExceptionGroup as eg:
            for _ in eg.exceptions:
                logger.exception(
                    "Error occurred while set key - %s  in multi level cache", key,
                )

    async def delete(self, key: str) -> None:
        """Параллельно удаляет ключ из обоих уровней кэша."""

        try:
            async with asyncio.TaskGroup() as tg:
                tg.create_task(self.l1_cache.delete(key))
                tg.create_task(self.l2_cache.delete(key))
        except ExceptionGroup as eg:
            for _ in eg.exceptions:
                logger.exception(
                    "Error occurred while delete key %s from multi level cache", key,
                )

    async def exists(self, key: str) -> bool:
        """Вернёт True если хотя бы на одном из уровней будет попадание."""

        return await self.l1_cache.exists(key) or await self.l2_cache.exists(key)


class CachedRepository[EntityT: Entity](RepositoryDecorator[EntityT]):
    def __init__(self, repo: Repository[EntityT], cache: Cache[EntityT], prefix: str) -> None:
        super().__init__(repo)
        self.cache = cache
        self.prefix = prefix

    async def create(self, entity: EntityT) -> EntityT:
        entity = await self._repo.create(entity)

        key = build_key(self.prefix, entity.id)
        await self.cache.set(key, entity)

        return entity

    async def read(self, uid: UUID) -> EntityT | None:
        key = build_key(self.prefix, uid)

        if entity := await self.cache.get(key) is not None:
            return entity

        entity = await self._repo.read(uid)

        if entity:
            await self.cache.set(key, entity)

        return entity

    async def update(self, entity: EntityT) -> None:
        """Обновление в БД + инвалидация кеша (обновление кеша при следующем чтении)."""

        await self._repo.update(entity)

        key = build_key(self.prefix, entity.id)
        await self.cache.delete(key)

    async def delete(self, uid: UUID) -> None:
        await self._repo.delete(uid)

        key = build_key(self.prefix, uid)
        await self.cache.delete(key)

    async def exists(self, uid: UUID) -> bool:
        """Не использует кеш, запрос идёт к источнику истины."""

        return await self._repo.exists(uid)
