"""add counterparty rel

Revision ID: f12bee4e7917
Revises: d349f6aa48f1
Create Date: 2026-03-17 10:56:02.342520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12bee4e7917'
down_revision: Union[str, Sequence[str], None] = 'd349f6aa48f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('counterparty_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'counterparties', ['counterparty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'counterparty_id')
    # ### end Alembic commands ###
