"""make inn non unique

Revision ID: 9c832b66ae74
Revises: c660fa491649
Create Date: 2026-04-01 15:02:10.488266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c832b66ae74'
down_revision: Union[str, Sequence[str], None] = 'c660fa491649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('counterparties_inn_key'), 'counterparties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('counterparties_inn_key'), 'counterparties', ['inn'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
