"""refactor tables

Revision ID: 8f49e9697b99
Revises: 55bb17ce9812
Create Date: 2026-03-30 12:49:32.884676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f49e9697b99'
down_revision: Union[str, Sequence[str], None] = '55bb17ce9812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('uploaded_by', sa.Uuid(), nullable=False))
    op.drop_column('attachments', 'uploaded_by_id')
    op.drop_column('counterparties', 'is_slave')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparties', sa.Column('is_slave', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('uploaded_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'uploaded_by')
    # ### end Alembic commands ###
