"""add number to tickets

Revision ID: 2dda19c2d711
Revises: 9c832b66ae74
Create Date: 2026-04-03 19:00:34.315107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dda19c2d711'
down_revision: Union[str, Sequence[str], None] = '9c832b66ae74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('number', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'tickets', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'number')
    # ### end Alembic commands ###
